import type { MarketParams } from "executooor-viem";
import type { Address, Hex } from "viem";
import { encodePacked, maxUint256, parseUnits } from "viem";

import type { LiquidationEncoder } from "./LiquidationEncoder.js";
import { MORPHO_BLUE } from "./morphoConstants.js";

export { MORPHO_BLUE };

/** Wrapped ETH (ETH mainnet). */
export const WETH: Address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";

/** Uniswap V3 SwapRouter (ETH mainnet). */
export const UNISWAP_V3_ROUTER: Address = "0xE592427A0AEce92De3Edee1F18E0157C05861564";

/** Default Uniswap V3 fee tier (0.3%). */
export const DEFAULT_UNI_FEE = 3000;

/** Minimum tip floor to avoid dust-level tips that builders ignore. */
const MIN_TIP_WEI = parseUnits("0.001", 18); // 0.001 ETH

/** Conservative tip estimate: 0.5% of seized collateral value. */
const TIP_BPS = 50n;
const BPS_DENOMINATOR = 10000n;

/**
 * Parameters for encoding a self-funding coinbase tip into the liquidation flow.
 */
export interface SelfFundingTipParams {
  /** Morpho Blue contract address. */
  morpho: Address;
  /** WETH address on this chain. */
  weth: Address;
  /** Uniswap V3 SwapRouter address. */
  uniV3Router: Address;
  /** The market being liquidated. */
  market: MarketParams;
  /** The borrower being liquidated. */
  borrower: Address;
  /** Collateral to seize (after buffer reduction). */
  seizableCollateral: bigint;
  /** Decimals of collateral token (18 for WETH/cbETH, 8 for cbBTC/WBTC). */
  collateralDecimals: number;
  /** Treasury address to receive remaining profit. */
  treasury: Address;
  /** Uniswap V3 fee tier for loanToken -> WETH swap (default: 3000 = 0.3%). */
  swapFeeTier?: number;
  /** Override tip amount instead of auto-estimating. */
  tipOverride?: bigint;
  /**
   * Pre-encoded liquidation callback calls (collateral -> loanToken conversion).
   * These are the calls generated by the liquidity venues that convert seized
   * collateral into loan tokens during the Morpho liquidation callback.
   */
  liquidationCallbackCalls: Hex[];
}

/**
 * Builds a packed Uniswap V3 swap path: tokenIn + fee + tokenOut.
 *
 * The path is ABI-encoded as: abi.encodePacked(address, uint24, address)
 * which is 20 bytes + 3 bytes + 20 bytes = 43 bytes total.
 *
 * For multi-hop paths, chain additional (fee, address) pairs.
 *
 * @param tokenIn - Input token address
 * @param tokenOut - Output token address
 * @param fee - Fee tier (e.g. 3000 for 0.3%, 500 for 0.05%, 10000 for 1%)
 * @returns ABI-encoded packed path for Uniswap V3 exactInput
 */
export function buildUniV3Path(tokenIn: Address, tokenOut: Address, fee: number): Hex {
  return encodePacked(["address", "uint24", "address"], [tokenIn, fee, tokenOut]);
}

/**
 * Estimates the tip amount in WETH (18 decimals).
 *
 * IMPORTANT: seizableCollateral may have different decimals than WETH (18).
 * For example, WBTC has 8 decimals. We normalize to 18 decimals before
 * calculating the tip to avoid unit mismatch bugs.
 *
 * Uses 0.5% of normalized seized collateral as a conservative estimate.
 * Clamped between MIN and MAX to avoid dust tips or excessive tips.
 *
 * @param seizableCollateral - Amount of collateral being seized (in collateral token units)
 * @param collateralDecimals - Decimals of the collateral token (default: 18)
 * @param overrideTip - Optional explicit tip amount in WETH wei (bypasses estimation)
 * @returns Tip amount in WETH wei (18 decimals, as bigint)
 */
export function estimateTipAmount(
  seizableCollateral: bigint,
  collateralDecimals = 18,
  overrideTip?: bigint,
): bigint {
  if (overrideTip !== undefined) {
    return overrideTip;
  }
  // Normalize to 18 decimals (WETH scale)
  const normalized =
    collateralDecimals === 18
      ? seizableCollateral
      : (seizableCollateral * 10n ** 18n) / 10n ** BigInt(collateralDecimals);

  const estimated = (normalized * TIP_BPS) / BPS_DENOMINATOR;

  // Clamp between min and max
  if (estimated < MIN_TIP_WEI) return MIN_TIP_WEI;
  if (estimated > MAX_TIP_WEI) return MAX_TIP_WEI;
  return estimated;
}

/** Maximum tip cap to prevent excessive spending. */
const MAX_TIP_WEI = parseUnits("0.05", 18); // 0.05 ETH (~$100)

/**
 * Encodes a self-funding coinbase tip into the liquidation transaction.
 *
 * For WETH loan markets:
 *   The liquidation profit is already in WETH. We simply unwrap a portion
 *   for the coinbase tip and skim the rest to treasury. No flash loan needed.
 *
 * For non-WETH loan markets (e.g. USDC, USDT):
 *   Flash loan WETH from Morpho (0% fee), unwrap to ETH, tip coinbase,
 *   execute the liquidation, then swap a portion of the loan token profit
 *   back to WETH to repay the flash loan.
 *
 * This makes the bot completely self-funding: no ETH balance required in
 * the wallet beyond gas costs. The tip comes from the liquidation profit itself.
 *
 * IMPORTANT: This function accumulates calls on the encoder. The caller must
 * call encoder.flush() after this to get the final call array.
 *
 * @param encoder - The LiquidationEncoder instance (calls accumulate on it)
 * @param params - Self-funding tip parameters
 * @returns The estimated tip amount used
 */
export function encodeSelfFundingTip(
  encoder: LiquidationEncoder,
  params: SelfFundingTipParams,
): bigint {
  const {
    morpho,
    weth,
    uniV3Router,
    market,
    borrower,
    seizableCollateral,
    collateralDecimals,
    treasury,
    swapFeeTier = DEFAULT_UNI_FEE,
    tipOverride,
    liquidationCallbackCalls,
  } = params;

  const tipAmount = estimateTipAmount(seizableCollateral, collateralDecimals, tipOverride);
  const isWethLoan = market.loanToken.toLowerCase() === weth.toLowerCase();

  if (isWethLoan) {
    // === WETH loan market: simple flow ===
    //
    // No flash loan needed. The liquidation produces WETH profit directly.
    //
    // Flow:
    //   1. Approve Morpho for loan token (WETH) repayment
    //   2. Liquidate (collateral -> WETH in callback)
    //   3. Unwrap WETH -> ETH for tip
    //   4. Tip coinbase
    //   5. Skim remaining WETH to treasury

    encoder.erc20Approve(market.loanToken, morpho, 0n);
    encoder.erc20Approve(market.loanToken, morpho, maxUint256);

    encoder.morphoBlueLiquidate(
      morpho,
      market,
      borrower,
      seizableCollateral,
      0n,
      liquidationCallbackCalls,
    );

    encoder.unwrapETH(weth, tipAmount);
    encoder.tip(tipAmount);
    encoder.erc20Skim(market.loanToken, treasury);
  } else {
    // === Non-WETH loan market: flash loan WETH for tip ===
    //
    // The liquidation profit is in a non-ETH token (e.g. USDC). We need ETH
    // for the coinbase tip, so we flash loan WETH from Morpho (0% fee).
    //
    // Execution order inside the executor contract:
    //
    //   [WETH Flash Loan Callback]:
    //     1. Unwrap WETH -> ETH (from flash loan)
    //     2. Tip coinbase with ETH
    //     3. Approve Morpho to pull loan tokens
    //     4. Liquidate (collateral -> loan token in callback)
    //     5. Swap loan token -> WETH (to repay flash loan)
    //     6. Approve Morpho to pull WETH (flash loan repayment)
    //   [End Callback: Morpho pulls WETH back]
    //
    //   7. Skim remaining loan token profit to treasury

    // Build the flash loan callback calls using the encoder's flush pattern.
    // We push all callback operations, flush to capture them, then use them
    // as the callback parameter for blueFlashLoan.

    // Step 1: Unwrap flash-loaned WETH to ETH
    encoder.unwrapETH(weth, tipAmount);

    // Step 2: Tip coinbase
    encoder.tip(tipAmount);

    // Step 3: Approve Morpho to pull loan tokens for liquidation repayment
    encoder.erc20Approve(market.loanToken, morpho, 0n);
    encoder.erc20Approve(market.loanToken, morpho, maxUint256);

    // Step 4: Liquidate with collateral -> loan token callback
    encoder.morphoBlueLiquidate(
      morpho,
      market,
      borrower,
      seizableCollateral,
      0n,
      liquidationCallbackCalls,
    );

    // Step 5: Swap loan token profit -> WETH to repay the flash loan.
    // Use exactOutput: we know exactly how much WETH we need (tipAmount),
    // and we're willing to spend up to maxUint256 of loanToken (the executor
    // holds the liquidation profit, and any excess stays for treasury skim).
    // NOTE: exactOutput path is reversed: WETH first, then loanToken.
    const swapPath = buildUniV3Path(weth, market.loanToken, swapFeeTier);
    encoder.uniV3ExactOutput(uniV3Router, swapPath, tipAmount, maxUint256);

    // Step 6: Approve Morpho to pull WETH for flash loan repayment
    encoder.erc20Approve(weth, morpho, tipAmount);

    // Flush all callback calls
    const flashLoanCallbackCalls = encoder.flush();

    // Wrap everything in a Morpho WETH flash loan (0% fee)
    encoder.blueFlashLoan(morpho, weth, tipAmount, flashLoanCallbackCalls);

    // Step 7: Skim remaining loan token profit to treasury
    encoder.erc20Skim(market.loanToken, treasury);
  }

  return tipAmount;
}
